### ISSUE TITLE
Zemberek parser'ı Flask-restful ile kullanılırken ikinci requestte hata alıyorum

### ISSUE THREAD

**Issue by gokhangerdan** [kemalcanbora/zemberek_parser#3]
Flask restful içerisinde kullandığımda ilk requestte beklediğim gibi çalışırken ikinci bir request gönderdiğimde aşağıdaki hatayı alıyorum:

```
  File "/home/ggerdan/.local/lib/python3.6/site-packages/zemberek_python/main_libs.py", line 61, in ogelere_ayir
    yanit = self.zemberek_api.kelimeCozumle(kelime)
AttributeError: 'NoneType' object has no attribute 'kelimeCozumle'
```

**Comment by farukbase** [comment]
Ben de zemberek_api ye erismeye calisirken NoneType object problemi ile karsilasiyorum. Hatayı deepdive etmeye calisirken de nesne yaratılırken java java.lang.nullpointerexception veriyor. Yuksek ihtimalle aynı yerden tetikleniyor.

**Comment by gokhangerdan** [comment]
@faruktufekci 
zemberek_grpc kullanmanı tavsiye ediyorum
https://pypi.org/project/zemberek-grpc/

**Comment by kemalcanbora** [comment]
herkese selamlar, kütüphane ile uğraşmayalı baya oldu yakın zamanda komple elden geçireceğim çünkü kimi makinelerde düzgün çalışırken kiminde bağımlı kütüphaneler yüklenmiyor bile bu süre zarfında eğer bu kütüphane ile uğraştıysanız ve hataları çözdüyseniz katkılarınızı bekliyorum seve seve mastera merge ederim
