### ISSUE TITLE
Dökümantasyon mevcut mu?

### ISSUE THREAD

**Issue by neslihanturan** [kemalcanbora/zemberek_parser#7]
Merhaba, java dosyalarını türkçeleştirmişsiniz sanırım. Dökümantasyonları mevcut mu? Veya zemberekte ingilizce olarak kullandığım methodların bire bir hangi methoda maplendiğini bulabileceğim bir şey?

**Comment by kemalcanbora** [comment]
hayır dokümantasyon mevcut değil. Method mapleri için java dosyasını inceleyebilirsiniz
